/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package talpa;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;

/**
 *
 * @author ruben
 */
public class FormAvvio extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormAvvio.class.getName());
    
    GestoreGioco g;
    Classifica c;
    /**
     * Creates new form FormAvvio
     */
    public FormAvvio(GestoreGioco g, Classifica c) {
        initComponents();
        
        this.g=g;
        this.c = c;
        
        JPanel panel = new JPanel() {
            Image imgSfondo = new ImageIcon("sfondoIniziale.png").getImage();
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                g.drawImage(imgSfondo, 0, 0, getWidth(), getHeight(), this);
            }
        };
        
        panel.setLayout(new BorderLayout());
        setContentPane(panel);

        JTextArea classificaArea = new JTextArea();
        classificaArea.setEditable(false);
        classificaArea.setFont(new Font("Arial", Font.BOLD, 24));
        classificaArea.setOpaque(false);
        classificaArea.setForeground(Color.WHITE);

        aggiornaClassifica(classificaArea);

        JScrollPane scroll = new JScrollPane(classificaArea);
        scroll.setOpaque(false);
        scroll.getViewport().setOpaque(false);
        panel.add(scroll, BorderLayout.CENTER);

        JButton avviaButton = new JButton("Avvia");
        avviaButton.setFont(new Font("Arial", Font.BOLD, 30));
        avviaButton.addActionListener(e -> {
            this.dispose();
            g.avviaGioco();
        });
        JPanel buttonPanel = new JPanel();
        buttonPanel.setOpaque(false);
        buttonPanel.add(avviaButton);
        panel.add(buttonPanel, BorderLayout.SOUTH);

        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void aggiornaClassifica(JTextArea area) {
        c.leggoClassifica();
        area.setText("");
        for (int i = 0; i < c.lista.size(); i++) {
            Giocatore g = c.lista.get(i);
            area.setText(area.getText() + (i+1) + ". " + g.nome + " - " + g.punti + "\n");
        }
    }    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
